name: Python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  node:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Fix Windows Git autocrlf
      run: git config --global core.autocrlf false
      if: matrix.os == 'windows-latest'
    - uses: actions/checkout@v2
    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    # - run: python3 -m flake8
    - run: python3 test.py tests/
      env:
        XUMM_APIKEY: aaaaaaaa-cccc-eeee-1111-333333333333
        XUMM_APISECRET: bbbbbbbb-dddd-ffff-2222-444444444444